### ISSUE TITLE
(0.4.0) queryList - the parameter 'mapper' is required

### ISSUE THREAD

**Issue by abhinavc** [vitusortner/floor#125]
Hi, 
Not sure if this is related to #113. But I have a simple DAO with the following query
```
@Query("select * from sports")
Future<List<Sport>> getAll() ;
```
However, I get the following compilation error 
```
lib/db/db.g.dart:70:35: Error: Too many positional arguments: 1 allowed, but 2 found.
Try removing the extra positional arguments.
    return _queryAdapter.queryList('select * from sports', _sportsMapper);
```
in the generated .part file 
```
@override
  Future<List<Sport>> getAll() async {
    return _queryAdapter.queryList('select * from sports', _sportsMapper);
  }
```
This started happening when I upgraded from 0.3.0 to 0.4.0. And I was upgrading because the code for inserting List<Sport> into the DB did not seem to be working in 0.3.0

**Comment by abhinavc** [comment]
My bad. I forgot to change the `floor_generator: 0.4.0` dependency in `pubspec.yaml`

But I still can't seem to insert records properly. For example, the following seems to work
`Future<void> insertAll(List<Sport>)`

But when I try to retrieve the just-added records using 
`Future<List<Sport>> getAll()`

all that I get is a list of records with every field `null`. Can't understand why

**Comment by abhinavc** [comment]
Problem was at my end - in the default constructor.
